### ISSUE TITLE
Deprivation coding

### ISSUE THREAD

**Issue by will-ball** [mysociety/composite_uk_imd#1]
Absolutely excellent work @ajparsons! I'm a user of the 2016 Abel et al adjusted index and have been considering updating it for a while too. I think it's a useful approach and especially useful for cross-national comparison.

One thing I would like to see is a clear explanation (e.g. in the README.md) of the direction of the deciles/quintiles. I know that the separate IMDs rank from 1 (most deprived) and most then follow that in the deciles/quintiles. I think for the ranks that makes sense but for quantiles it can be counterintuitive for some - personally I prefer to see deprivation increase with the quantile number. But that's just a personal preference.

If you could make it explicit which end of the quantiles is most or least deprived (e.g. the deprivation distribution section of the README.md) that would help a reader.

**Comment by ajparsons** [comment]
I definitely got confused by this when first started working with indexes and agree the convention is not always initiative. 

I'm going to add something along these lines:

### Interpreting scores, ranks, deciles and quintiles

For users new to indexes of deprivation it is not always clear which direction is "worse". This set of indexes follows the general convention that:

* Higher scores show 'worse' deprivation. The most deprived area is the one with the highest score.
* For ranks this flips around, Rank 1 is the most deprived area. 
* Deciles and Quintiles follow ranks. Decile 1 and Quintile 1 are the most deprived decile and quintile respectively. 

So if plotting a column graph of deprivation deciles from 1-10, the most deprived decile is on the far left. This may differ from the initiative sense that in a measure of deprivation higher numbers mean more deprivation, but this maintains consistency with how deciles are generated by the individual indexes. 

Explored in more detail below, but we do not recommend relying too much on raw score in this dataset as the theoretical basis for precise rankings is less robust. The exception to this is the `employment` score in the UK indexes, and the `employment` and `income` scores in the GB indexes, as these are based on similar underlying indicators.

**Comment by will-ball** [comment]
Looks great Alex!
